name: Maven Package

on:
  push:
    branches: [ "crac-release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: ./mvnw -B install
        -Dmaven.source.skip=true -DskipTests -DskipITs -DskipDocs
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}
        MAVEN_OPTS: -Xmx1563m

    - run: ./mvnw -B deploy
        -Dmaven.source.skip=true -DskipTests -DskipITs -DskipDocs
        -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}
        MAVEN_OPTS: -Xmx1563m
